### PR TITLE
249 auto skip action does not work

### LINKED ISSUE #249: [BUG] AUTO_SKIP action does not work
## Describe the bug
The AUTO_SKIP action does not make text autoskip.

## Steps To Reproduce

- Play 1-4-JoryWitnessTestimony
- Play until tutorial boy says "Witness, state y-"
- The game waits for player input

## Expected behavior
The game should automatically play Jory's next line "I'm sorry! Please forgive me!!!"

### PR DESCRIPTION
**Pull request by PhoebeMitchell**
## Summary

Fixes the bug described in #249.
Removes UnityEvents from AppearingDialogueController in favour of direct references.
Adds some tests for the auto-skip action and the continue arrow.

## Testing instructions

Play 1-4-JoryWitnessTestimony. Notice how the game autoskips when Tutorial Boy says "Witness, state y-".
Run the associated tests.

## Additional information

- `[ ]` Changes UI
- `[ ]` Introduces new feature
- `[ ]` Removes existing feature
- `[x]` Has associated resource: 
  
closes #249

### CODE REVIEW

File: unity-ggjj/Assets/Scripts/UI/AppearingDialogueController/AppearingDialogueController.cs [hunk 1]
```diff
@@ -38,11 +38,7 @@ public class AppearingDialogueController : MonoBehaviour, IAppearingDialogueCont
     [Tooltip("Specify how often a chirp should play here")]
     [SerializeField] private int _chirpEveryNthLetter = 1;
 
-    
-    [field:Header("Events")]
-    [field:SerializeField] public UnityEvent OnLineEnd { get; private set; }
-    [SerializeField] private UnityEvent _onAutoSkip;
-    [SerializeField] private UnityEvent _onLetterAppear;
```
Comment (ViMaSter) [inline unity-ggjj/Assets/Scripts/UI/AppearingDialogueController/AppearingDialogueController.cs:45]: image

**Review by ViMaSter — APPROVED** [review]
GitHub plz giv `if (source.linesOfCode < target.linesOfCode && source.coverage > target.coverage && builds.All(build=>build.success) && tests.All(test=>test.success) approve();` kthxbye

---

The simplified integration tests for the `AppearingDialogueController` should be reason enough to merge this in (so much easier to read now), but it _also_ fixes a bug. Sounds like a perfect PR to me. 👍

**Review by notexplosive — APPROVED** [review]
yeos
